function show(X){
		if(X==1)
		{
	       $(".I1").css('display','inline-block');
		}
		if(X==2)
		{
		    $(".I2").css('display','inline-block');
		}
		if(X==3)
		{
		    $(".I3").css('display','inline-block');
		}
		if(X==4)
		{
		    $(".I4").css('display','inline-block');
		}
	}
function hiddenP(X)
	{
		if(X==1)
		{
	       $(".I1").css('display','none');
		}
		if(X==2)
		{
	       $(".I2").css('display','none');
		}
		if(X==3)
		{
	       $(".I3").css('display','none');
		}
		if(X==4)
		{
	      $(".I4").css('display','none');
		}
	}
function showE(){
		 $('.S2-IME').addClass('S2-IM');
}
function hiddenE(){
		 $('.S2-IME').removeClass('S2-IM');
}
function showS6(X){
		if(X==1)
		{
	       $(".G1").css('display','inline-block');
		}
		if(X==2)
		{
		    $(".G2").css('display','inline-block');
		}
		if(X==3)
		{
		    $(".G3").css('display','inline-block');
		}
		if(X==4)
		{
		    $(".G4").css('display','inline-block');
		}
		if(X==5)
		{
		    $(".G5").css('display','inline-block');
		}
		if(X==6)
		{
		    $(".G6").css('display','inline-block');
		}
		if(X==7)
		{
		    $(".G7").css('display','inline-block');
		}
		if(X==8)
		{
		    $(".G8").css('display','inline-block');
		}
		if(X==9)
		{
		    $(".G9").css('display','inline-block');
		}
	}
function hiddenS6(X)
	{
		if(X==1)
		{
	       $(".G1").css('display','none');
		}
		if(X==2)
		{
	       $(".G2").css('display','none');
		}
		if(X==3)
		{
	       $(".G3").css('display','none');
		}
		if(X==4)
		{
	      $(".G4").css('display','none');
		}
		if(X==5)
		{
	      $(".G5").css('display','none');
		}
		if(X==6)
		{
	      $(".G6").css('display','none');
		}
		if(X==7)
		{
	      $(".G7").css('display','none');
		}
		if(X==8)
		{
	      $(".G8").css('display','none');
		}
		if(X==9)
		{
	      $(".G9").css('display','none');
		}
	}